version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: task-management-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend service
  backend:
    build: ./backend
    container_name: task-management-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/task-management
      - JWT_SECRET=your-secret-key-for-development-only
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service (Next.js)
  frontend-next:
    build: ./frontend-next/frontend-next
    container_name: task-management-frontend-next
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

# Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge